openapi: 3.0.0
info:
  title: MediConnectDz API
  version: 1.0.0
  description: API documentation for MediConnectDz backend
servers:
  - url: http://localhost:5000
paths:
  /auth/register:
    post:
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                userId:
                  type: string
                name:
                  type: string
                email:
                  type: string
                password:
                  type: string
                role:
                  type: string
                subscriptionPlan:
                  type: string
                subscriptionDuration:
                  type: integer
      responses:
        '201':
          description: User registered
        '400':
          description: Registration error
  /auth/login:
    post:
      summary: Login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                userId:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Login successful
        '401':
          description: Incorrect password
        '404':
          description: User not found
  /profile/{userId}:
    get:
      summary: Get user profile
      parameters:
        - in: path
          name: userId
          required: true
          schema:
            type: string
      responses:
        '200':
          description: User profile
        '404':
          description: User not found
    put:
      summary: Update user profile
      parameters:
        - in: path
          name: userId
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
      responses:
        '200':
          description: Profile updated
        '404':
          description: User not found
  /appointments/book:
    post:
      summary: Book an appointment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                doctorId:
                  type: string
                date:
                  type: string
                  format: date-time
      responses:
        '201':
          description: Appointment booked
        '400':
          description: Booking error
  /chat/room:
    post:
      summary: Create or get a chat room
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                userId1:
                  type: string
                userId2:
                  type: string
                type:
                  type: string
      responses:
        '200':
          description: Chat room
  /chat/message:
    post:
      summary: Send a message
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                roomId:
                  type: string
                senderId:
                  type: string
                content:
                  type: string
      responses:
        '201':
          description: Message sent
  /chat/messages/{roomId}:
    get:
      summary: Get messages for a chat room
      parameters:
        - in: path
          name: roomId
          required: true
          schema:
            type: string
      responses:
        '200':
          description: List of messages 